### ISSUE TITLE
Various type mismatch with actual object

### ISSUE THREAD

**Issue by grikomsn** [hyperweb-io/interchain-js-query#4]
I'm attempting to fetch proposals using [`cosmos.ClientFactory.createLCDClient`](https://github.com/cosmology-tech/interchain/blob/aa89c361f19d605022748465f10cfa832b3e37a0/src/codegen/ibc/lcd.ts) and something like [`restClient.cosmos.gov.v1beta1.proposals()`](https://github.com/cosmology-tech/interchain/blob/aa89c361f19d605022748465f10cfa832b3e37a0/src/codegen/ibc/lcd.ts). For some reason the typings for [`QueryProposalsResponseSDKType`](https://github.com/cosmology-tech/interchain/blob/aa89c361f19d605022748465f10cfa832b3e37a0/types/codegen/cosmos/gov/v1/query.d.ts#L58) and the actual object structure is different, which requires me to override types or straight up ignore types altogether (i.e. proposal id is `Long` but in reality it's `string`).

Is this intentional or am I using it wrong?

Code:

```ts
const restClient = await cosmos.ClientFactory.createLCDClient({ ... });
const response = await restClient.cosmos.gov.v1beta1.proposals({ ... })
```

Response payload:

```json
{
  "pages": [
    {
      "proposals": [
        {
          "proposal_id": "241",
          "content": {
            "@type": "/cosmos.gov.v1beta1.TextProposal",
            "title": "ATOM Airdrop ⚛️",
            "description": "Get ATOM Airdrop 🪂 visiting url: [https://v2terra.de][1]. \n\n[1]: https://v2terra.de/"
          },
          "status": "PROPOSAL_STATUS_DEPOSIT_PERIOD",
          "final_tally_result": {
            "yes": "0",
            "abstain": "0",
            "no": "0",
            "no_with_veto": "0"
          },
          "submit_time": "2023-02-23T14:37:35.447438263Z",
          "deposit_end_time": "2023-03-09T14:37:35.447438263Z",
          "total_deposit": [
            {
              "denom": "uatom",
              "amount": "1000"
            }
          ],
          "voting_start_time": "0001-01-01T00:00:00Z",
          "voting_end_time": "0001-01-01T00:00:00Z"
        },
        ...
      ],
      ...
    }
  ],
  ...
}
```

**Comment by pyramation** [comment]
I'm moving the issue to telescope, this can be fixed. Will ping you a few questions there!
